/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierental;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Actor extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Actor() {
        initComponents();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_input = new javax.swing.JButton();
        f_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        l_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datetime = new javax.swing.JTextField();
        id_actor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbActor = new javax.swing.JTable();
        b_refresh = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_edit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\kuliah\\SEMESTER IV\\Business Application Development\\BG\\bg2.jpg")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\kuliah\\SEMESTER IV\\Business Application Development\\BG\\bg3.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_input.setFont(new java.awt.Font("Clarendon BT", 0, 11)); // NOI18N
        b_input.setText("INPUT");
        b_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_inputMouseClicked(evt);
            }
        });
        b_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_inputActionPerformed(evt);
            }
        });
        getContentPane().add(b_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 97, 96, 29));

        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        getContentPane().add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 156, 201, 30));

        jLabel1.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel1.setText("FIRST NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));
        getContentPane().add(l_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 219, 202, 29));

        jLabel2.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel2.setText("LAST NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        datetime.setEditable(false);
        getContentPane().add(datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 275, 202, 29));
        getContentPane().add(id_actor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 97, 200, 29));

        jLabel3.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 97, 35, 29));

        tbActor.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        tbActor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "First_Name", "Last_name", "last_update"
            }
        ));
        tbActor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbActorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbActor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 144, 423, 160));

        b_refresh.setFont(new java.awt.Font("Clarendon BT", 0, 11)); // NOI18N
        b_refresh.setText("REFRESH");
        b_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_refreshMouseClicked(evt);
            }
        });
        getContentPane().add(b_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 97, -1, 29));

        b_delete.setFont(new java.awt.Font("Clarendon BT", 0, 11)); // NOI18N
        b_delete.setText("DELETE");
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(b_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 97, 90, 29));

        jLabel4.setFont(new java.awt.Font("Clarendon Blk BT", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("INPUT DATA AKTOR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 410, 34));

        jLabel5.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel5.setText("LAST UPDATE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 281, -1, -1));

        b_edit.setFont(new java.awt.Font("Clarendon BT", 0, 11)); // NOI18N
        b_edit.setText("EDIT");
        getContentPane().add(b_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 97, 92, 29));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\kuliah\\SEMESTER IV\\Business Application Development\\BG\\bg7.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 70, 850, 260));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\kuliah\\SEMESTER IV\\Business Application Development\\BG\\bg9.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_inputActionPerformed
        // TODO add your handling code here:
//        Connection connection;
//        PreparedStatement ps;
//        try {
//            connection = DriverManager.getConnection("jdbc:mysql://localhost/movie_rental?zeroDateTimeBehavior=convertToNull", "root" , "");
//            ps = connection.prepareStatement("SELECT email, password FROM staff WHERE email = ? AND password = ?");
//            ps.setString(1, email.getText());
//            ps.setString(2, password.getText());
//            ResultSet result = ps.executeQuery();
//            if(result.next()){
//                new Dashboard().show();
//                this.dispose();
//            }else{
//                JOptionPane.showMessageDialog(rootPane, "Salah!");
//                password.setText("");
//                email.requestFocus();
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(rootPane, "Gagal");
//        }

        if ("".equals(id_actor.getText())||"".equals(f_name.getText())||"".equals(l_name.getText())||
                "".equals(datetime.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);    
        }else{
            
            String SQL = "INSERT INTO actor (ID,First_Name,Last_Name,last_update) "
                    + "VALUES('"+id_actor.getText()+"','"+f_name.getText()+"','"+l_name.getText()+"','"+datetime.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_b_inputActionPerformed

    private void b_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_inputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b_inputMouseClicked

    private void tbActorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbActorMouseClicked
        // TODO add your handling code here:
        int baris = tbActor.getSelectedRow();
        if (baris != -1) {
            id_actor.setText(tbActor.getValueAt(baris, 0).toString());
            f_name.setText(tbActor.getValueAt(baris, 1).toString());
            l_name.setText(tbActor.getValueAt(baris, 2).toString());
            datetime.setText(tbActor.getValueAt(baris, 3).toString());
        }
        
    }//GEN-LAST:event_tbActorMouseClicked

    private void b_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_refreshMouseClicked
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_b_refreshMouseClicked

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        int baris = tbActor.getSelectedRow();
        if (baris != -1) {
            String id_actor = tbActor.getValueAt(baris, 0).toString();
            String SQL = "DELETE * FROM tbActor WHERE id_actor='"+id_actor+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_b_deleteActionPerformed

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actor().setVisible(true);
            }
        });
        
        
        
    }
    
    public JTable getTableData(){
        return tbActor;
    }
    
    private void setTanggal() {
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new
       java.text.SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
       datetime.setText(kal.format(skrg));
    }
    
    private void selectData() {
        String kolom[] = {"ID","First_Name","Last_Name","last_update"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM actor";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while (rs.next()) {
                String ID = rs.getString(1);
                String First_Name = rs.getString(2);                  
                String Last_name = rs.getString(3);
                String last_update = rs.getString(4);
                String data[] = {ID,First_Name,Last_name,last_update};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(Actor.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbActor.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_edit;
    private javax.swing.JButton b_input;
    private javax.swing.JButton b_refresh;
    private javax.swing.JTextField datetime;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField id_actor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_name;
    private javax.swing.JTable tbActor;
    // End of variables declaration//GEN-END:variables
}
