/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierental;

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Staff extends javax.swing.JFrame {
    
    private KoneksiDB db = new KoneksiDB();

    /**
     * Creates new form FilmActor
     */
    public Staff() {
        initComponents();
        selectData();
        cbAddress();
        cbStore();
        setTanggal();
    }
    
    private void setTanggal() {
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new
       java.text.SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
       last_update.setText(kal.format(skrg));
    }
    
    public void cbStore(){
        String SQL = "SELECT * FROM store";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {            
            while (rs.next()) {                
                cb_store.addItem(rs.getString("ID"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        } catch (SQLException e) {
        }
    }

    public void cbAddress(){
        String SQL = "SELECT * FROM address";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {            
            while (rs.next()) {                
                cb_address.addItem(rs.getString("ID"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        } catch (SQLException e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbStore = new javax.swing.JTable();
        b_refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_address = new javax.swing.JComboBox<>();
        last_update = new javax.swing.JTextField();
        b_input = new javax.swing.JButton();
        tb_id = new javax.swing.JTextField();
        cb_store = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tb_fname = new javax.swing.JTextField();
        tb_lname = new javax.swing.JTextField();
        tb_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tb_active = new javax.swing.JTextField();
        tb_coloumn = new javax.swing.JTextField();
        tb_password = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        b_attach = new javax.swing.JButton();
        pict = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbStore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "filmID", "ActorID", "last_update"
            }
        ));
        jScrollPane1.setViewportView(tbStore);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 140, 513, 130);

        b_refresh.setText("REFRESH");
        b_refresh.setToolTipText("");
        b_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_refreshMouseClicked(evt);
            }
        });
        getContentPane().add(b_refresh);
        b_refresh.setBounds(330, 260, 77, 23);

        jLabel1.setText("Store");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 26, 14);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 160, 39, 14);

        getContentPane().add(cb_address);
        cb_address.setBounds(110, 150, 102, 20);

        last_update.setEditable(false);
        getContentPane().add(last_update);
        last_update.setBounds(110, 380, 102, 20);

        b_input.setText("INPUT");
        b_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_inputMouseClicked(evt);
            }
        });
        b_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_inputActionPerformed(evt);
            }
        });
        getContentPane().add(b_input);
        b_input.setBounds(110, 420, 124, 23);

        tb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_idActionPerformed(evt);
            }
        });
        getContentPane().add(tb_id);
        tb_id.setBounds(110, 120, 102, 20);

        getContentPane().add(cb_store);
        cb_store.setBounds(110, 190, 102, 20);

        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 11, 14);
        getContentPane().add(tb_fname);
        tb_fname.setBounds(110, 210, 102, 20);
        getContentPane().add(tb_lname);
        tb_lname.setBounds(110, 240, 102, 20);
        getContentPane().add(tb_email);
        tb_email.setBounds(110, 260, 102, 20);

        jLabel4.setText("first name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 48, 14);

        jLabel5.setText("last name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 46, 14);

        jLabel6.setText("email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 270, 24, 14);
        getContentPane().add(tb_active);
        tb_active.setBounds(110, 290, 102, 20);
        getContentPane().add(tb_coloumn);
        tb_coloumn.setBounds(110, 320, 102, 20);
        getContentPane().add(tb_password);
        tb_password.setBounds(110, 350, 102, 20);

        jLabel7.setText("active");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 290, 29, 12);

        jLabel8.setText("coloumn");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 320, 39, 14);

        jLabel9.setText("password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 350, 46, 14);

        jLabel10.setText("last update");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 380, 54, 14);

        b_attach.setText("ATTACH");
        b_attach.setToolTipText("");
        b_attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_attachActionPerformed(evt);
            }
        });
        getContentPane().add(b_attach);
        b_attach.setBounds(330, 350, 73, 23);

        pict.setEditable(false);
        getContentPane().add(pict);
        pict.setBounds(330, 320, 182, 20);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(560, 20, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_refreshMouseClicked
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_b_refreshMouseClicked

    private void b_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_inputMouseClicked
        // TODO add your handling code here:
        if ("".equals(tb_id.getText())||"".equals(cb_address.getSelectedItem())||"".equals(cb_store.getSelectedItem())||
                "".equals(tb_fname.getText())||"".equals(tb_lname.getText())||"".equals(tb_email.getText())||
                "".equals(tb_active.getText())||"".equals(tb_coloumn.getText())||"".equals(tb_password.getText())||
                "".equals(last_update.getText())||"".equals(pict.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);    
        }else{
            
            String SQL = "INSERT INTO staff (ID,AddressID,StoreID,Firstname,Lastname,email,active,coloumn,Pasword,last_update,PictureURL) "
                    + "VALUES('"+tb_id.getText()+"','"+cb_address.getSelectedItem()+"','"+cb_store.getSelectedItem()
                    +"','"+tb_fname.getText()+"','"+tb_lname.getText()+"','"+tb_email.getText()+"','"+tb_active.getText()
                    +"','"+tb_coloumn.getText()+"','"+tb_password.getText()+"','"+last_update.getText()+"','"+pict.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_b_inputMouseClicked

    private void tb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_idActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tb_idActionPerformed

    private void b_attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_attachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        pict.setText(filename);
//        Image getAbsoluthPath = null;
//        ImageIcon icon = new ImageIcon(filename);
//        Image image = icon.getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH);
//        img.setIcon(icon);
        
    }//GEN-LAST:event_b_attachActionPerformed

    private void b_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_inputActionPerformed

    private void selectData() {
        String kolom[] = {"ID","addressID","StoreID","Firstname","Lastname","email","active","coloumn","Pasword","Last_Update","PictureURL"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM staff";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while (rs.next()) {
                String ID = rs.getString(1);                  
                String addressID = rs.getString(2);
                String StoreID = rs.getString(3);
                String Firstname = rs.getString(4);
                String Lastname = rs.getString(5);
                String email = rs.getString(6);
                String active = rs.getString(7);
                String coloumn = rs.getString(8);
                String Pasword = rs.getString(9);
                String last_update = rs.getString(10);
                String PictureURL = rs.getString(11);
                String data[] = {ID,addressID,StoreID,Firstname,Lastname,email,coloumn,Pasword,last_update,PictureURL};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(Actor.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbStore.setModel(dtm);
    }
    
    public JTable getTableData(){
        return tbStore;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_attach;
    private javax.swing.JButton b_input;
    private javax.swing.JButton b_refresh;
    private javax.swing.JComboBox<String> cb_address;
    private javax.swing.JComboBox<String> cb_store;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_update;
    private javax.swing.JTextField pict;
    private javax.swing.JTable tbStore;
    private javax.swing.JTextField tb_active;
    private javax.swing.JTextField tb_coloumn;
    private javax.swing.JTextField tb_email;
    private javax.swing.JTextField tb_fname;
    private javax.swing.JTextField tb_id;
    private javax.swing.JTextField tb_lname;
    private javax.swing.JTextField tb_password;
    // End of variables declaration//GEN-END:variables
}
